#!/bin/bash

# prepare variables
#
client_id=fff007a807304b9a8d983f5eaa095c98
client_name=admin_client
client_secret=secret

user_id=3b23023b725c4262934d7339556b6d2d
username=admin@example.com
password=123

authserver_url=http://localhost:8282
authadmin_url=http://localhost:8080/v1

echo "******************************************************************************************"
echo "test reads for clients"

echo ""
echo "1) verify list all clients from authadmin server without access_token"
echo ""
cmd="curl -is -X GET '${authadmin_url}/clients'"
echo "$cmd"
response=$(eval "$cmd")
RESULT=$?

echo "$response"

if [ $RESULT -eq 0 ]; then
  echo "success"
else
  echo "failed to run "$cmd""
  exit 1
fi

response_code=$(echo "$response" | head -n 1 | awk '{ print $2 }')

if [ "$response_code" != "401" ]; then
    echo "not http unauthorize"
    exit 1
fi


echo ""
echo "2) use grant_type=password to get access_token & refresh_token from authserver"
echo ""
cmd="curl -sS -X POST -u '$client_id:$client_secret' '$authserver_url/oauth/v1/token' -d 'grant_type=password&username=$username&password=$password'"
echo "$cmd"
response=$(eval "$cmd")

RESULT=$?

echo "$response"

if [ $RESULT -eq 0 ]; then
  echo "success"
else
  echo "failed to run "$cmd""
  exit 1
fi

access_token=$(echo "$response" | jq '.access_token' | sed -e 's/^"//' -e 's/"$//')
if [ "$access_token" == "null" ]; then
    echo "access_token is null"
    exit 1;
fi

echo "access_token=$access_token"

refresh_token=$(echo "$response" | jq '.refresh_token' | sed -e 's/^"//' -e 's/"$//')
if [ "$refresh_token" == "null" ]; then
    echo "refresh_token is null"
    exit 1;
fi

echo "refresh_token=$refresh_token"

echo ""
echo "3) list all clients from authadmin server"
echo ""
cmd="curl -sS -H 'Authorization: Bearer $access_token' -X GET '${authadmin_url}/clients'"
echo "$cmd"
response=$(eval "$cmd")
RESULT=$?

echo "$response"

if [ $RESULT -eq 0 ]; then
  echo "success"
else
  echo "failed to run "$cmd""
  exit 1
fi

count=$(echo "$response" | grep $client_name | wc -l)
if [ "$count" -eq 0 ]; then
  echo "result is not OK(1)"
  exit 1
fi

client_urls=$(echo "$response" | grep $authadmin_url/clients/ | awk '{print $3}' | uniq |  tr -d '"')
if [ -z "$client_urls" ]; then
  echo "result is not OK(2)"
  exit 1
fi

client_ids=$(echo "$client_urls" | grep -v search | awk -F '/' '{ print $6 }');
if [ -z "$client_ids" ]; then
  echo "result is not OK(3)"
  exit 1
fi

client_names=$(echo "$response" | grep client_name | awk '{print $3}' | tr -d '"' | tr -d ',');

if [ -z "$client_names" ]; then
  echo "result is not OK(4)"
  exit 1
fi

echo ""
echo "4) get each client from authadmin server"
echo ""

while read -r client_url; do
  
  if [[ "$client_url" == *"-secret" ]]; then
    continue
  fi
  
  cmd="curl -sS -H 'Authorization: Bearer $access_token' -X GET '$client_url'"
  echo "$cmd"
  response=$(eval "$cmd")
  RESULT=$?

  echo "$response"

  if [ $RESULT -eq 0 ]; then
    echo "success"
  else
    echo "failed to run "$cmd""
    exit 1
  fi

  if [[ "$client_url" == */search ]]; then
    echo "has search url"
  else
  count=$(echo "$response" | grep client_name | wc -l)
    if [ "$count" -ne 1 ]; then
        echo "result is not OK"
        exit 1
    fi
  fi
done <<< "$client_urls"

echo ""
echo "5) use search/findByClientId to get each user from authadmin server"
echo ""

while read -r client_id; do
  cmd="curl -sS -H 'Authorization: Bearer $access_token' -X GET '$authadmin_url/clients/search/ids?id=$client_id'"
  echo "$cmd"
  response=$(eval "$cmd")
  RESULT=$?

  echo "$response"

  if [ $RESULT -eq 0 ]; then
    echo "success"
  else
    echo "failed to run "$cmd""
    exit 1
  fi

  count=$(echo "$response" | grep client_name | wc -l)
  if [ "$count" -ne 1 ]; then
    echo "result is not OK"
    exit 1
  fi

done <<< "$client_ids"

echo ""
echo "6) use search/findByClientName to get each user from authadmin server"
echo ""

while read -r client_name; do
  cmd="curl -sS -H 'Authorization: Bearer $access_token' -X GET '$authadmin_url/clients/search/client-names?name=$client_name'"
  echo "$cmd"
  response=$(eval "$cmd")
  RESULT=$?

  echo "$response"

  if [ $RESULT -eq 0 ]; then
    echo "success"
  else
    echo "failed to run "$cmd""
    exit 1
  fi

  count=$(echo "$response" | grep client_name | wc -l)
  if [ "$count" -ne 1 ]; then
    echo "result is not OK"
    exit 1
  fi

done <<< "$client_names"

echo "------------------------------------------------------------------------------------------"
echo "test completed successfully"
